# Generated by Django 3.1 on 2020-12-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0003_auto_20201202_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
